version: '3'
services:
  pg:
     image: citusdata/citus:12.0.0-alpine
     ports:
       - 5432:5432
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
